export const cats = [
  {
    id: 'cat-1',
    name: 'Маргарита',
    price: 3500,
    description: 'Классический ласковый котик для уютных вечеров.',
    imageUrl: '/static/1.jpg',
  },
  {
    id: 'cat-2',
    name: 'Пепперони',
    price: 4200,
    description: 'Очень активный котик, всегда в движении.',
    imageUrl: '/static/2.jpg',
  },
  {
    id: 'cat-3',
    name: 'Четыре сыра',
    price: 5100,
    description: 'Мягкий, пушистый и обнимабельный.',
    imageUrl: '/static/3.jpg',
  },
  {
    id: 'cat-4',
    name: 'Ветчина и грибы',
    price: 3900,
    description: 'Игривый котик, любит активные игры и компанию.',
    imageUrl: '/static/4.jpg',
  },
  {
    id: 'cat-5',
    name: 'Барбекю',
    price: 4400,
    description: 'Котик с ярким характером, но очень преданный.',
    imageUrl: '/static/5.jpg',
  },
  {
    id: 'cat-6',
    name: 'Гавайская',
    price: 3800,
    description: 'Солнечный и дружелюбный котик, любит внимание.',
    imageUrl: '/static/6.jpg',
  },
  {
    id: 'cat-7',
    name: 'Мясная',
    price: 4600,
    description: 'Крупный котик, любит поесть и долго спать.',
    imageUrl: '/static/7.jpg',
  },
  {
    id: 'cat-8',
    name: 'Диабло',
    price: 4700,
    description: 'Очень энергичный котик, идеален для активных хозяев.',
    imageUrl: '/static/8.jpg',
  },
  {
    id: 'cat-9',
    name: 'Четыре сезона',
    price: 4300,
    description: 'Универсальный котик, подойдёт под любое настроение.',
    imageUrl: '/static/9.jpg',
  },
];
